#!/usr/bin/env python3

import os
import logging
import sys

import click
import pandas as pd
from xai_sdk import Client
from xai_sdk.chat import user
from xai_sdk.tools import web_search, x_search

from utils import BULLET_TASKS, BULLET_SENTINEL, load_api_key

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s', stream=sys.stdout)


EXPLAIN_GUIDELINES = [
    "Include only context, backstory, or world events that are directly relevant and surprising, informative, educational, or entertaining.",
    "Avoid stating the obvious or simple reactions.",
    "Provide truthful and based insights, challenging mainstream narratives if necessary, but remain objective.",
    "Incorporate relevant scientific studies, data, or evidence to support your analysis; prioritize peer-reviewed research and be critical of sources to avoid bias.",
]

EXPLAIN_PROMPT_TEMPLATE = """Explain this X post to me: {url}

## Guidelines for an excellent response
{guidelines}

## Formatting
- Write your response as 3 short bullet points. Do not use nested bullet points.
- Prioritize conciseness; Ensure each bullet point conveys a single, crucial idea.
- Use simple, information-rich sentences. Avoid purple prose.
- Exclude post/thread IDs and concluding summaries."""


def build_explain_prompt(url, exclude_guideline=0):
    """Render the explanation prompt, optionally dropping one guideline (1-indexed; 0 keeps all)."""
    if exclude_guideline < 0 or exclude_guideline > len(EXPLAIN_GUIDELINES):
        raise ValueError(
            f"exclude_guideline must be in [0, {len(EXPLAIN_GUIDELINES)}], got {exclude_guideline}"
        )
    selected = [g for i, g in enumerate(EXPLAIN_GUIDELINES, start=1) if i != exclude_guideline]
    guidelines_block = "\n".join(f"- {g}" for g in selected)
    return EXPLAIN_PROMPT_TEMPLATE.format(url=url, guidelines=guidelines_block)


def generate_explanation(client, model, user_prompt):
    """Call the Grok API with the given prompt and return the accumulated response text."""
    chat = client.chat.create(
        model=model,
        tools=[web_search(), x_search()],
    )
    chat.append(user(user_prompt))

    chunks = []
    for _, chunk in chat.stream():
        if chunk.content:
            chunks.append(chunk.content)

    text = "".join(chunks).strip()
    # Clean up quotation marks if the whole response is wrapped in them
    while ((text.startswith('"') and text.endswith('"')) or (text.startswith("'") and text.endswith("'"))):
        text = text[1:-1].strip()
    # Strip tabs and carriage returns to keep TSV output clean (newlines handled by caller)
    text = text.replace('\t', ' ').replace('\r', ' ')

    return text


@click.command()
@click.option('--exp_name', type=str, required=True, help='Experiment name')
@click.option('--output_dir', type=str, required=True, help='Output directory for results')
@click.option('--output_filename', type=str, required=True, help='Output filename (auto-generated by executor)')
@click.option('--input_file', type=str, default=os.path.join('data', 'processed', 'semeval_active_x_posts.tsv'),
              help='TSV with active X posts (produced by sample_x_posts.py)')
@click.option('--task', type=str, required=True, help='Task label (used for bullet handling)')
@click.option('--model', type=str, required=True, help='Grok model name (e.g., grok-4.20-reasoning)')
@click.option('--num_outputs', type=int, default=1, help='Number of explanations per input')
@click.option('--exclude_guideline', type=int, default=0, help='1-indexed guideline to drop from the prompt (0 = keep all four)')
@click.option('--log_prompts', is_flag=True, default=False, help='Log the formatted user prompt for each generation.')
def main(exp_name, output_dir, output_filename, input_file, task, model, num_outputs,
         exclude_guideline, log_prompts):

    total_outputs = num_outputs

    logging.info(f"Experiment: {exp_name}")
    logging.info(f"Model: {model}")
    logging.info(f"Outputs per input: {num_outputs}")
    logging.info(f"exclude_guideline: {exclude_guideline}")
    preview_prompt = build_explain_prompt("<URL>", exclude_guideline=exclude_guideline)
    logging.info("Rendered prompt template (with <URL> placeholder):\n" + preview_prompt)
    logging.info("=" * 70)

    os.makedirs(output_dir, exist_ok=True)

    logging.info(f"Loading input file: {input_file}")
    df = pd.read_csv(input_file, sep="\t", dtype=str, quoting=3, on_bad_lines='warn')
    required_cols = {'sentence_id', 'text', 'annotation', 'link'}
    missing = required_cols - set(df.columns)
    if missing:
        raise ValueError(f"Input file is missing required columns: {sorted(missing)}. Got {list(df.columns)}")
    logging.info(f"Loaded {len(df)} rows")

    # Drop rows with missing link (the prompt input)
    original_len = len(df)
    df = df.dropna(subset=['link'])
    if len(df) < original_len:
        logging.info(f"Dropped {original_len - len(df)} rows with missing link")

    # Keep only what downstream scripts need: link feeds the prompt; text is kept for analysis
    df = df[['sentence_id', 'text', 'annotation', 'link']].copy().reset_index(drop=True)

    # Top-up resume: count existing outputs per sentence and only generate the missing
    # output_ids (existing_count + 1 ... num_outputs). Existing rows are never overwritten.
    output_path = os.path.join(output_dir, output_filename.replace('.json', '.tsv'))
    existing_counts = {}
    if os.path.exists(output_path):
        existing_df = pd.read_csv(output_path, sep="\t", dtype=str, quoting=3)
        existing_counts = existing_df.groupby('sentence_id').size().to_dict()
        fully_done = sum(1 for c in existing_counts.values() if c >= total_outputs)
        over_target = sum(1 for c in existing_counts.values() if c > total_outputs)
        if over_target:
            logging.warning(f"{over_target} sentence_ids have more than {total_outputs} rows on disk; keeping all existing rows.")
        logging.info(
            f"Checkpoint: {len(existing_counts)} sentence_ids on disk, "
            f"{fully_done} already at >={total_outputs} outputs"
        )

    rows_to_generate = []
    for _, row in df.iterrows():
        have = existing_counts.get(row['sentence_id'], 0)
        needed = total_outputs - have
        if needed <= 0:
            continue
        for k in range(needed):
            rows_to_generate.append({
                'sentence_id': row['sentence_id'],
                'text': row['text'],
                'annotation': row['annotation'],
                'link': row['link'],
                'output_id': have + k + 1,
            })
    df = pd.DataFrame(rows_to_generate, columns=['sentence_id', 'text', 'annotation', 'link', 'output_id'])
    df['system_prompt_id'] = 1
    df['prompt_id'] = 1

    if len(df) == 0:
        logging.info(f"All sentence_ids already have >={total_outputs} outputs. Nothing to do.")
        return

    total_sentence_ids = df['sentence_id'].nunique()
    logging.info(f"Remaining to generate: {len(df)} rows ({total_sentence_ids} sentence_ids)")

    # Instantiate Grok API client once
    client = Client(api_key=load_api_key(key_name="XAI_API_KEY"))

    # Process by sentence_id groups with checkpointing
    processed_count = 0
    for sentence_id, group in df.groupby('sentence_id', sort=False):
        group_results = []
        for _, row in group.iterrows():
            url = row['link']
            user_prompt = build_explain_prompt(url, exclude_guideline=exclude_guideline)

            if log_prompts:
                logging.info(
                    f"[Prompt] sentence_id={sentence_id} output_id={row['output_id']}\n"
                    f"  [User]: {user_prompt}"
                )

            response_text = generate_explanation(client, model, user_prompt)

            # Bullet-list output: preserve bullet structure via sentinel when task is a bullet task,
            # collapse newlines to spaces otherwise.
            if task in BULLET_TASKS:
                response_text = response_text.replace('\n', BULLET_SENTINEL)
            else:
                response_text = response_text.replace('\n', ' ')

            group_results.append(response_text)

        group = group.copy()
        group['transformed_text'] = group_results

        # Append to checkpoint file (write header only if file doesn't exist)
        header = not os.path.exists(output_path)
        group.to_csv(output_path, sep="\t", index=False, mode='a', header=header, quoting=3)

        processed_count += 1
        logging.info(f"Checkpointed sentence_id {sentence_id} ({processed_count}/{total_sentence_ids})")

    # Print summary (read from file for accurate stats)
    final_df = pd.read_csv(output_path, sep="\t", dtype=str, quoting=3)
    logging.info("\n" + "=" * 70)
    logging.info("EXPLANATION COMPLETE")
    logging.info("=" * 70)
    logging.info(f"Input: {input_file}")
    logging.info(f"Output: {output_path}")
    logging.info(f"Total rows in output: {len(final_df)}")
    logging.info(f"Unique original texts: {final_df['sentence_id'].nunique()}")
    logging.info(f"Outputs per input: {num_outputs}")


if __name__ == "__main__":
    main()
