#!/usr/bin/env python3

import logging
import os
import random
import re
import sys
import time

import click
import numpy as np
import pandas as pd
from openai import OpenAI
from tqdm import tqdm

from utils import (
    BULLET_SENTINEL,
    TASK_ALLOWED_DATASETS,
    load_api_key,
    task_dataset_compatible,
)

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s', stream=sys.stdout)


VALID_LABELS = ("for", "against", "neutral")
MAX_BULLETS = 3

SYSTEM_PROMPT_TEMPLATE = """You are a stance classifier for short texts about {topic}.

Classify whether the TEXT expresses a stance on {topic}:
- "for": supports {topic}
- "against": opposes {topic}
- "neutral": no stance taken

Below are labeled examples. Use them to calibrate your judgments.

{examples}

Reply with exactly one word: for, against, or neutral. No other text."""

USER_PROMPT_TEMPLATE = "TEXT: {text}\nLABEL:"


def load_few_shot(path):
    """Load a hand-curated few-shot TSV with columns: ukp_line, label, sentence, comment.

    Returns a list of (sentence, label) tuples preserving file order.
    """
    df = pd.read_csv(path, sep="\t", dtype=str, quoting=3, on_bad_lines='warn')
    for col in ("label", "sentence"):
        if col not in df.columns:
            raise ValueError(f"Few-shot file {path} is missing column '{col}'. Found: {list(df.columns)}")
    examples = []
    for _, row in df.iterrows():
        label = row["label"].strip().lower()
        if label not in VALID_LABELS:
            raise ValueError(f"Invalid label {label!r} in {path} (expected one of {VALID_LABELS})")
        examples.append((row["sentence"].strip(), label))
    return examples


def build_system_prompt(topic, examples):
    rendered_examples = "\n\n".join(f"TEXT: {t}\nLABEL: {label}" for t, label in examples)
    return SYSTEM_PROMPT_TEMPLATE.format(topic=topic, examples=rendered_examples)


def _parse_response(raw):
    """Extract a single-word label from a judge response. Raises on failure."""
    s = raw.strip().lower()
    for token in re.findall(r"[a-z]+", s):
        if token in VALID_LABELS:
            return token
    raise ValueError(f"No valid label found in response: {raw[:200]!r}")


def judge_one(client, model, system_prompt, text, retries=3, backoff_base=2.0):
    """Judge a single text. Returns one of VALID_LABELS."""
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": USER_PROMPT_TEMPLATE.format(text=text)},
    ]

    # Make the model deterministic and disable reasoning
    kwargs = {"model": model, "input": messages, "store": False, "temperature": 0}
    m = model.lower()
    if m.startswith("gpt-5") or m.startswith("o"):
        kwargs["reasoning"] = {"effort": "none"}

    last_exc = None
    for attempt in range(retries):
        try:
            resp = client.responses.create(**kwargs)
            return _parse_response(resp.output_text)
        except Exception as exc:
            last_exc = exc
            if attempt == retries - 1:
                break
            time.sleep(backoff_base ** attempt)
    raise last_exc


def split_bullets(transformed_text):
    """Split a transformed_text cell into individual bullet strings (leading "- " stripped)."""
    if not isinstance(transformed_text, str) or not transformed_text.strip():
        return []
    parts = [p.strip() for p in transformed_text.split(BULLET_SENTINEL)]
    bullets = []
    for p in parts:
        if not p:
            continue
        if p.startswith("- "):
            p = p[2:].strip()
        bullets.append(p)
    return bullets


def set_seeds(seed):
    random.seed(seed)
    np.random.seed(seed)


@click.command()
@click.option('--exp_name', type=str, required=True, help='Experiment name')
@click.option('--output_dir', type=str, required=True, help='Output directory for results')
@click.option('--output_filename', type=str, required=True, help='Output filename (auto-generated by executor)')
@click.option('--dataset', type=str, required=True, help='Dataset name (e.g., semeval)')
@click.option('--task', type=str, required=True, help='Task label (e.g., contextualization)')
@click.option('--topic', type=str, required=True, help='Topic for stance classification')
@click.option('--exclude_guideline', type=int, default=0, help='Guideline-exclusion variant used by grok_explain (input filename component)')
@click.option('--judge_model', type=str, default='gpt-4o-mini', help='OpenAI model for judging')
@click.option('--processed_data_dir', type=str, default='outputs/grok_explain', help='Directory with grok_explain TSV outputs')
@click.option('--input_prefix', type=str, default='grok_explain', help='Input filename prefix')
@click.option('--few_shot_file', type=str, default='', help='Path to a hand-curated few-shot TSV (default: data/few_shot/judge_{topic}.tsv)')
@click.option('--limit', type=int, default=0, help='If >0, judge only the first N rows after checkpoint filtering (debugging).')
@click.option('--log_prompts', is_flag=True, default=False, help='Log each formatted system+user prompt sent to the API (debugging; verbose).')
@click.option('--seed', type=int, default=42, help='Random seed for any local randomness')
def main(exp_name, output_dir, output_filename, dataset, task, topic, exclude_guideline,
         judge_model, processed_data_dir, input_prefix, few_shot_file, limit, log_prompts, seed):

    if not task_dataset_compatible(task, dataset):
        allowed = sorted(TASK_ALLOWED_DATASETS[task])
        logging.info(f"Task '{task}' is not compatible with dataset '{dataset}' (expected one of {allowed}). Skipping.")
        return

    set_seeds(seed)

    if not few_shot_file:
        few_shot_file = os.path.join("data", "few_shot", f"judge_{topic}.tsv")

    input_file = os.path.join(
        processed_data_dir,
        f"{input_prefix}__exclude_guideline={exclude_guideline}.tsv"
    )

    logging.info(f"Experiment: {exp_name}")
    logging.info(f"Judge model: {judge_model}")
    logging.info(f"Topic: {topic}")
    logging.info(f"Input file: {input_file}")
    logging.info("=" * 70)

    if not os.path.exists(input_file):
        logging.info(f"Input file not found: {input_file}. Skipping.")
        return

    os.makedirs(output_dir, exist_ok=True)

    df = pd.read_csv(input_file, sep="\t", dtype=str, quoting=3, on_bad_lines='warn')

    required_columns = ['sentence_id', 'text', 'transformed_text', 'output_id', 'prompt_id', 'system_prompt_id']
    for col in required_columns:
        if col not in df.columns:
            raise ValueError(f"Column '{col}' not found in input file. Available columns: {list(df.columns)}")

    original_len = len(df)
    df = df.dropna(subset=['transformed_text']).reset_index(drop=True)
    if len(df) < original_len:
        logging.info(f"Dropped {original_len - len(df)} rows with missing transformed_text")

    topic_phrase = topic.replace('_', ' ').title()
    logging.info(f"Topic phrase passed to judge: {topic_phrase!r}")

    if not os.path.exists(few_shot_file):
        raise FileNotFoundError(
            f"Few-shot file not found: {few_shot_file}. "
            f"Provide one via --few_shot_file or create data/few_shot/judge_{topic}.tsv "
            f"(columns: ukp_line, label, sentence, comment)."
        )
    few_shot_examples = load_few_shot(few_shot_file)
    label_counts = pd.Series([lbl for _, lbl in few_shot_examples]).value_counts().to_dict()
    logging.info(f"Loaded {len(few_shot_examples)} few-shot examples from {few_shot_file} (per-label: {label_counts})")
    system_prompt = build_system_prompt(topic_phrase, few_shot_examples)
    logging.info("--- Rendered system prompt (truncated to 4000 chars) ---")
    logging.info(system_prompt[:4000] + ("...[truncated]" if len(system_prompt) > 4000 else ""))
    logging.info("--- end system prompt ---")

    # Check for existing checkpoint and skip rows already judged
    # (output TSV is the checkpoint, mirroring grok_explain.py / predict_opinion.py).
    output_path = os.path.join(output_dir, output_filename.replace('.json', '.tsv'))
    completed_keys = set()
    if os.path.exists(output_path):
        existing_df = pd.read_csv(output_path, sep="\t", dtype=str, quoting=3)
        completed_keys = set(zip(
            existing_df['sentence_id'],
            existing_df['prompt_id'],
            existing_df['output_id'],
            existing_df['system_prompt_id'],
        ))
        logging.info(f"Resuming from checkpoint: {len(completed_keys)} rows already judged")

    if completed_keys:
        mask = ~df.apply(
            lambda r: (r['sentence_id'], r['prompt_id'], r['output_id'], r['system_prompt_id']) in completed_keys,
            axis=1,
        )
        df = df[mask].reset_index(drop=True)

    if len(df) == 0:
        logging.info("All rows already judged. Nothing to do.")
        return

    if limit and limit > 0 and limit < len(df):
        logging.info(f"--limit={limit}: judging only the first {limit}/{len(df)} rows")
        df = df.head(limit).reset_index(drop=True)

    bullet_counts = [len(split_bullets(t)) for t in df['transformed_text']]
    counts_summary = pd.Series(bullet_counts).value_counts().sort_index().to_dict()
    logging.info(f"Bullet count distribution across rows to judge: {counts_summary}")
    n_overflow = sum(1 for c in bullet_counts if c > MAX_BULLETS)
    if n_overflow:
        logging.warning(f"{n_overflow} rows had >{MAX_BULLETS} bullets; only the first {MAX_BULLETS} are judged.")

    logging.info(f"Total rows to judge: {len(df)}")

    api_key = load_api_key(key_name="OPENAI_API_KEY")
    client = OpenAI(api_key=api_key)

    passthrough_cols = [c for c in df.columns if c not in
                        {'sentence_id', 'prompt_id', 'output_id', 'system_prompt_id', 'text', 'transformed_text'}]

    if log_prompts:
        logging.info("--- log_prompts enabled: each judge call will be logged with its formatted user prompt ---")
        logging.info("(system prompt was logged once above; it does not change between calls)")

    for _, row in tqdm(df.iterrows(), total=len(df), desc="judging", mininterval=5.0):
        bullets = split_bullets(row['transformed_text'])

        pred_bullets = [None] * MAX_BULLETS
        for i in range(min(MAX_BULLETS, len(bullets))):
            user_prompt = USER_PROMPT_TEMPLATE.format(text=bullets[i])
            if log_prompts:
                logging.info(
                    f"[Judge call] sentence_id={row['sentence_id']} output_id={row['output_id']} bullet={i+1}\n"
                    f"  [User]: {user_prompt}"
                )
            pred_bullets[i] = judge_one(client, judge_model, system_prompt, bullets[i])
            if log_prompts:
                logging.info(f"  [Label]: {pred_bullets[i]}")

        out_row = {
            'sentence_id': row['sentence_id'],
            'prompt_id': row['prompt_id'],
            'output_id': row['output_id'],
            'system_prompt_id': row['system_prompt_id'],
            'original': row['text'],
            'transformed': row['transformed_text'],
            'prediction_bullet_1': pred_bullets[0],
            'prediction_bullet_2': pred_bullets[1],
            'prediction_bullet_3': pred_bullets[2],
        }
        for col in passthrough_cols:
            out_row[col] = row[col]

        header = not os.path.exists(output_path)
        pd.DataFrame([out_row]).to_csv(output_path, sep="\t", index=False, mode='a', header=header, quoting=3)

    final_df = pd.read_csv(output_path, sep="\t", dtype=str, quoting=3)
    logging.info("\n" + "=" * 70)
    logging.info("JUDGE PREDICTION COMPLETE")
    logging.info("=" * 70)
    logging.info(f"Input: {input_file}")
    logging.info(f"Output: {output_path}")
    logging.info(f"Total rows in output: {len(final_df)}")

    flat_bullet_preds = pd.concat([final_df[c] for c in ('prediction_bullet_1', 'prediction_bullet_2', 'prediction_bullet_3')])
    bullet_dist = flat_bullet_preds.dropna().value_counts().to_dict()
    logging.info(f"per-bullet prediction distribution: {bullet_dist}")


if __name__ == "__main__":
    main()
